#File name without extention must match with spring.application.name in application.yml file of a microsercice
---
message: Hello World From Spring Config Server!!!

greetings: Hppy New Year From Config Server

list:
    values: one,two,three,four

#properties for configuration beans 
db:
  connection: database-connection-url-from-config-server
  user: leon
  password: lion
  maxConnections: 50
  port: 1522